import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, Container, Stack, Typography } from "@mui/material";
import { Toastify } from "./Toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Supermercados Credfranco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={inter.className}>
        <main>
          <Container>
            <Stack minHeight="100vh">
              <Box borderBottom="3px solid">
                <Typography variant="h2" textAlign="center">
                  Supermercado Credifranco
                </Typography>
              </Box>
              <Stack
                flexGrow={1}
                justifyContent="center"
                alignItems="center"
                sx={{
                  backgroundImage: "url(./market-stock.jpg)",
                  backgroundRepeat: "no-repeat",
                  backgroundSize: "cover",
                }}
              >
                <Stack
                  direction="row"
                  justifyContent="space-around"
                  flexGrow={0.7}
                  width="80%"
                  boxSizing="border-box"
                  sx={{ backgroundColor: "#FFFFFFAA" }}
                >
                  {children}
                </Stack>
              </Stack>
            </Stack>
          </Container>
          <Toastify />
        </main>
      </body>
    </html>
  );
}
